In [6]:
# stats.zscore() method 
import numpy as np 
from scipy import stats 
	
arr1 = [[20, 2, 7, 1, 34], 
		[50, 12, 12, 34, 4]] 

arr2 = [[50, 12, 12, 34, 4], 
		[12, 11, 10, 34, 21]] 

print ("\narr1 : ", arr1) 
print ("\narr2 : ", arr2) 

print ("\nZ-score for arr1 : \n", stats.zscore(arr1)) 
print ("\nZ-score for arr2 : \n", stats.zscore(arr2, axis = 1)) 




arr1 :  [[20, 2, 7, 1, 34], [50, 12, 12, 34, 4]]

arr2 :  [[50, 12, 12, 34, 4], [12, 11, 10, 34, 21]]

Z-score for arr1 : 
 [[-1. -1. -1. -1.  1.]
 [ 1.  1.  1.  1. -1.]]

Z-score for arr2 : 
 [[ 1.62005758 -0.61045648 -0.61045648  0.68089376 -1.08003838]
 [-0.61601725 -0.72602033 -0.83602341  1.80405051  0.37401047]]
